### ISSUE TITLE
Headers illegible due to theme colours

### ISSUE THREAD

**Issue by AndrewDDavis** [sswatson/table-editor-vscode#3]
In my current theme (Light+) the text is almost illegible in the column headers and in cells being edited, because the cell background colour is almost the same as the text colour.

Can you direct me to where the extension is pulling the header background colour from, or whether it is an editable setting?

**Comment by sswatson** [comment]
Thanks for pointing this out. I just hadn't tried it in light mode, so I hadn't noticed this. I can update the extension so that it works in both light and dark mode.

**Comment by sswatson** [comment]
This is now available in version 0.3.7.
