### ISSUE TITLE
Wrap support?

### ISSUE THREAD

**Issue by ickc** [sswatson/table-editor-vscode#4]
Would you consider adding options to wrap long cells in the editor?

Thanks.

**Comment by sswatson** [comment]
Great request. Support for multiline cells went in in `v0.3.10`, which just hit the Extension Marketplace.

The way it works is that you can convert a cell to multiline by right-clicking a cell and choosing "Convert to multiline". Alternatively, if a cell is multiline in the original CSV, it's automatically multiline.

Multiline cells open a `textarea` element for editing in a multiline-appropriate way. You can press "Escape" when you're done editing, or click off of the editor.
