### ISSUE TITLE
JSON conversion when some fields are null

### ISSUE THREAD

**Issue by goldova** [sswatson/table-editor-vscode#5]
Is there any way to work with jsons havings null values in some entries?
I managed to properly convert json into table, null values are converted into empty cells.
But when I insert edited data as JSON, empty cells are not saved as NULL values, but as empty strings.

**Comment by sswatson** [comment]
Thanks for flagging this issue. The behavior I observed when I tested this is different from what you're describing, but it was undesired behavior nonetheless.

In the latest version on the Marketplace (`v0.3.14`), `null`s successfully round-trip from JSON to the table editor back to JSON. Let me know if this works for your use case.

**Comment by goldova** [comment]
indeed works ok, thank you
